baseURL: /
languageCode: en-us
title: Sam Neirinck
theme: future-imperfect
preserveTaxonomyNames: true
paginate: 3
disqusShortname: samneirinck
googleAnalytics: UA-54270449-2
pluralizeListTitles: false
params:
  description: Sam Neirinck - My little stories
  navbarTitle: Sam Neirinck
  viewMorePostLink: /blog/
  dynamicTitles: true
  rssAppearAtTop: true
  rssAppearAtBottom: true
  socialAppearAtTop: false
  socialAppearAtBottom: true
  categoriesByCount: true
  includeReadingTime: true
  loadFavicon: false
  faviconVersion: ''
  socialShare: false
  customCSS:
    - default
  customJS:
    - default
  staticman:
    staticman: false
    username: ''
    repo: ''
    branch: ''
  intro:
    header: Sam Neirinck
    paragraph: YOLO <i class='fa fa-hand-peace-o'></i>
    about: Always
    pic:
      src: /img/main/logo.png
      circle: false
      imperfect: true
      width: ''
      alt: Sam Neirinck
  postAmount:
    sidebar: 5
menu:
  main:
    - name: Home
      url: /
      identifier: fa fa-home
      weight: 1
    - name: Blog
      url: /blog/
      identifier: fa fa-newspaper-o
      weight: 2
    - name: About
      url: /about/
      identifier: fa fa-id-card-o
      weight: 3
    - name: Contact
      url: /contact/
      identifier: fa fa-envelope-o
      weight: 4
social:
  github: samneirinck
  twitter: samneirinck
  linkedin: sam-neirinck-3ba3551a
  email: info@samneirinck.com
permalinks:
  blog: '/:year/:month/:title'
