baseurl         = "/"
title           = "Sam Neirinck"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "samneirinck"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true


[params]
  title       = "Sam Neirinck"
  subtitle    = "developer of useless things"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = "UA-54270449-2"
  customCSS = []
  RSSLink = ""

  twitterName = "samneirinck"
  githubName = "samneirinck"
  linkedinName = "samneirinck"

  #logo = "hugo-logo.png"
  orgName = "Sam Neirinck"
  orgWebsite = "https://www.samneirinck.com"

  showSupport = true

  author = "Sam Neirinck"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://www.samneirinck.com"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 100


